# Generated by Django 6.0 on 2025-12-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
            ],
        ),
    ]
